-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.car
(
    id serial NOT NULL,
    model character varying(255) NOT NULL,
    year_model date NOT NULL,
    line_id integer NOT NULL,
    CONSTRAINT "PK_id_car" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."package"
(
    id serial NOT NULL,
    line character varying(255) NOT NULL,
    CONSTRAINT "PK_line_id" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.component
(
    id serial NOT NULL,
    name character varying NOT NULL,
    CONSTRAINT "PK_id_component" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sub_component
(
    id serial NOT NULL,
    name character varying(255) NOT NULL,
    qty integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.provider
(
    id serial NOT NULL,
    name character varying(255) NOT NULL,
    sub_id integer NOT NULL,
    CONSTRAINT "PK_provider_id" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.package_assembly
(
    car_id integer NOT NULL,
    line_id integer NOT NULL,
    component_id integer NOT NULL,
    qty_component integer NOT NULL,
    sub_id integer NOT NULL,
    qty_sub integer NOT NULL
);

ALTER TABLE IF EXISTS public.car
    ADD CONSTRAINT "FK_id_line" FOREIGN KEY (line_id)
    REFERENCES public."package" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.provider
    ADD CONSTRAINT "FK_sub_component_id" FOREIGN KEY (sub_id)
    REFERENCES public.sub_component (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.package_assembly
    ADD CONSTRAINT "FK_line_id" FOREIGN KEY (line_id)
    REFERENCES public."package" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.package_assembly
    ADD CONSTRAINT "FK_car_id" FOREIGN KEY (car_id)
    REFERENCES public.car (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.package_assembly
    ADD CONSTRAINT "FK_component_id" FOREIGN KEY (component_id)
    REFERENCES public.component (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.package_assembly
    ADD CONSTRAINT "FK_sub_id" FOREIGN KEY (sub_id)
    REFERENCES public.sub_component (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;